namespace PingYi.App;

public static partial class UiText
{
    // Bilingual runtime resources; no generated user content or credentials.
    private static readonly IReadOnlyDictionary<string, (string Chinese, string English)> UiResources =
        new Dictionary<string, (string Chinese, string English)>(StringComparer.Ordinal)
    {
        ["String.AppName"] = ("屏译", "PingYi"),
        ["String.AppTagline"] = ("截图、识别、翻译，一次完成", "Capture, recognize, and translate in one step"),
        ["String.Close"] = ("关闭", "Close"),
        ["String.CopyAll"] = ("复制全部", "Copy all"),
        ["String.CopySource"] = ("复制原文", "Copy source"),
        ["String.CopyTranslation"] = ("复制译文", "Copy translation"),
        ["String.OpenSettings"] = ("打开设置", "Open settings"),
        ["String.ResultTitle"] = ("识别结果", "Recognition results"),
        ["String.Retry"] = ("重新处理", "Process again"),
        ["String.StartCapture"] = ("开始截图", "Start capture"),
        ["Ui.PolishText.CaptureCancelHint"] = ("按 Esc 取消框选", "Press Esc to cancel a selection"),
        ["Ui.PolishText.CaptureShortHint"] = ("框选屏幕文字，让识别与翻译自然发生。", "Select screen text. Let recognition and translation follow."),
        ["Ui.PolishText.CaptureShortTitle"] = ("截图取词，自在阅读。", "Capture text. Keep reading."),
        ["Ui.PolishText.DataBoundary"] = ("数据与隐私", "Data & privacy"),
        ["Ui.PolishText.RecognitionGroup"] = ("文字识别", "Text recognition"),
        ["Ui.PolishText.TranslationGroup"] = ("翻译偏好", "Translation preferences"),
        ["Ui.Text.01197746a1c6"] = ("显示或隐藏", "Show or hide"),
        ["Ui.Text.01f61382b4b0"] = ("正在处理截图内容", "Processing captured content"),
        ["Ui.Text.02739d1bae8b"] = ("服务地址", "Endpoint"),
        ["Ui.Text.0299dc01919c"] = ("全局快捷键", "Global shortcut"),
        ["Ui.Text.032eb48c7a43"] = ("复制译文", "Copy translation"),
        ["Ui.Text.035be0663f55"] = ("Google OCR 凭据：正在检查安全存储…", "Google OCR credential: checking secure storage…"),
        ["Ui.Text.07dfec93a84e"] = ("识别到的原文", "Recognized source text"),
        ["Ui.Text.085931b25c71"] = ("本地优先", "Local first"),
        ["Ui.Text.0a6515fe343a"] = ("刷新模型与服务状态", "Refresh model and service status"),
        ["Ui.Text.0af5623919d4"] = ("保存并验证凭据", "Save and verify credentials"),
        ["Ui.Text.0f66607cd07e"] = ("翻译 APP ID", "Translation APP ID"),
        ["Ui.Text.122f7fe9c7c6"] = ("截图、识别原文、译文和密钥不会写入应用日志；不保存截图或翻译历史。结果窗口及重试所需内容只保留在运行内存中。", "Application logs do not contain images, recognized text, translations or credentials. No capture or translation history is saved. Result windows and retry data stay in running memory only."),
        ["Ui.Text.13434c003ced"] = ("例如 gemma-4-e4b-it", "e.g. gemma-4-e4b-it"),
        ["Ui.Text.160fa36bfe38"] = ("翻译提供商", "Translation provider"),
        ["Ui.Text.17b67e10f03b"] = ("固定结果卡", "Pin result card"),
        ["Ui.Text.193ed23a3e22"] = ("中英互译与日常取词，不需要联网。", "Everyday text extraction and Chinese–English translation, without a network."),
        ["Ui.Text.1bd1893c0900"] = ("准备就绪", "Ready"),
        ["Ui.Text.1f06472ae882"] = ("Google 翻译凭据：正在检查安全存储…", "Google Translation credential: checking secure storage…"),
        ["Ui.Text.1fef86b64588"] = ("百度 OCR Secret Key", "Baidu OCR Secret Key"),
        ["Ui.Text.21a71618bad2"] = ("正在检查完整模型包…", "Checking the complete model package…"),
        ["Ui.Text.23daf4d7881a"] = ("百度翻译 APP ID", "Baidu Translation APP ID"),
        ["Ui.Text.24cd2dadb9a2"] = ("保存所有设置", "Save all settings"),
        ["Ui.Text.28137e0aafbe"] = ("完全版 · 一键本机多模态模型", "Complete edition · One-click local multimodal model"),
        ["Ui.Text.2888370272ee"] = ("检查处理引擎状态", "Check processing engine status"),
        ["Ui.Text.2b153304b138"] = ("测试图片", "Test image"),
        ["Ui.Text.2cd0f3be8738"] = ("取消", "Cancel"),
        ["Ui.Text.2e8a27d3a971"] = ("复制原文", "Copy source"),
        ["Ui.Text.2f3956618152"] = ("选择方案后，按需配置模型或凭据。语言选择立即保存并切换，其他设置使用保存并应用。", "Choose a scheme, then configure any required models or credentials. Language changes apply immediately; use Save and apply for other settings."),
        ["Ui.Text.301e7d783f53"] = ("该密钥由你自己的 Google Cloud 项目提供；建议只允许调用 Cloud Vision API 与 Cloud Translation API。截图仅在选择 Google OCR 时上传，翻译只上传识别后的文字。", "Use an API key from your own Google Cloud project and restrict it to Cloud Vision and Cloud Translation. Images are uploaded only when Google OCR is selected; translation uploads recognized text only."),
        ["Ui.Text.31882138222f"] = ("反馈问题", "Report an issue"),
        ["Ui.Text.33af5784c71b"] = ("测试翻译", "Test translation"),
        ["Ui.Text.33d52a191ec3"] = ("语言选择后立即保存并生效，不会丢失其他未保存的输入。", "Language changes are saved and applied immediately. Other unsaved fields are preserved."),
        ["Ui.Text.354b28c85333"] = ("原文", "Source"),
        ["Ui.Text.378c7842fe76"] = ("翻译凭据：正在检查安全存储…", "Translation credentials: checking secure storage…"),
        ["Ui.Text.3a57aee6d162"] = ("屏译", "PingYi"),
        ["Ui.Text.3ce928cae715"] = ("重新识别和翻译", "Recognize and translate again"),
        ["Ui.Text.3d13868593ae"] = ("界面语言", "Interface language"),
        ["Ui.Text.3fd47edce45b"] = ("关闭", "Close"),
        ["Ui.Text.415c32ababe7"] = ("翻译模型：正在检查…", "Translation model: checking…"),
        ["Ui.Text.42910cbc1cab"] = ("服务预设", "Service preset"),
        ["Ui.Text.43fb060119c0"] = ("屏译结果", "PingYi Results"),
        ["Ui.Text.44ac539067ed"] = ("本地模型", "Local models"),
        ["Ui.Text.487c5545cad9"] = ("应用方案", "Apply scheme"),
        ["Ui.Text.492a56a00f11"] = ("打开下载页", "Open download page"),
        ["Ui.Text.4986d0c80645"] = ("下载中英翻译模型", "Download Chinese/English translation model"),
        ["Ui.Text.49c172bca9d1"] = ("显示 OCR API Key", "Show OCR API Key"),
        ["Ui.Text.49e1e6be89fd"] = ("翻译结果", "Translation result"),
        ["Ui.Text.4a2df84f92d0"] = ("显示 Google Cloud API Key", "Show Google Cloud API Key"),
        ["Ui.Text.4a456bc2336f"] = ("选择界面语言", "Choose interface language"),
        ["Ui.Text.4aa2ad79923b"] = ("请检查模型或服务配置。", "Check the model or service configuration."),
        ["Ui.Text.4b9659ed544c"] = ("帮助与关于", "Help & About"),
        ["Ui.Text.4daf6c2b1b4f"] = ("应用服务预设", "Apply service preset"),
        ["Ui.Text.4e1449e7d5e5"] = ("显示", "Show"),
        ["Ui.Text.4e435fe44aef"] = ("打开模型目录", "Open model folder"),
        ["Ui.Text.5159e7c4e585"] = ("复制原文和译文", "Copy source and translation"),
        ["Ui.Text.517daccd5094"] = ("Esc 取消", "Esc to cancel"),
        ["Ui.Text.520b00e114f7"] = ("尚未保存", "Not saved"),
        ["Ui.Text.52e1279ef29c"] = ("显示翻译 APP ID", "Show translation APP ID"),
        ["Ui.Text.5412c737687b"] = ("启动并应用", "Start and apply"),
        ["Ui.Text.5850d0183e6c"] = ("兼容翻译接口 API Key", "Compatible endpoint API Key"),
        ["Ui.Text.5cd84648726b"] = ("自动翻译", "Automatic translation"),
        ["Ui.Text.5eda20b4e81b"] = ("显示兼容接口 API Key", "Show compatible endpoint API Key"),
        ["Ui.Text.5fd5df38157d"] = ("文字识别", "Text recognition"),
        ["Ui.Text.63b8870a1ef4"] = ("模型下载、凭据验证和更新检查会访问相应服务。自动更新检查默认关闭，可在外观与启动中管理。", "Model downloads, credential validation and update checks contact their respective services. Automatic update checks are off by default and can be managed in Appearance & startup."),
        ["Ui.Text.63d90d977348"] = ("复制", "Copy"),
        ["Ui.Text.660640f5b06f"] = ("正在识别…", "Recognizing…"),
        ["Ui.Text.69f42967a6d8"] = ("百度 OCR API Key", "Baidu OCR API Key"),
        ["Ui.Text.6f4f62913d52"] = ("立即修复", "Fix now"),
        ["Ui.Text.7116a6da8a30"] = ("选择翻译方案", "Choose a translation scheme"),
        ["Ui.Text.71456ea2891f"] = ("保存并验证 Google 凭据", "Save and verify Google credentials"),
        ["Ui.Text.72a5e7ce2caf"] = ("OCR 模型：正在检查…", "OCR model: checking…"),
        ["Ui.Text.77bad5f6137e"] = ("百度 OCR 与翻译凭据", "Baidu OCR and Translation credentials"),
        ["Ui.Text.7e0abe191612"] = ("只下载当前选择的 GGUF 与视觉投影文件；下载支持断点续传并强制校验 SHA-256。模型在本机端口 18080 运行，截图和文字不会离开设备。", "Downloads only the selected GGUF and vision projector files, with resume support and mandatory SHA-256 verification. The model runs locally on port 18080; screenshots and text stay on this device."),
        ["Ui.Text.7ebc37fcf513"] = ("多模态 OCR 会发送本次框选图片；127.0.0.1 服务不会离开设备。", "Multimodal OCR sends the selected image; loopback services at 127.0.0.1 stay on this device."),
        ["Ui.Text.80461c2decc5"] = ("译文", "Translation"),
        ["Ui.Text.8480e4db725a"] = ("Windows 10/11 x64 与 Ubuntu X11 x64。项目源码采用 MIT 许可证；模型和第三方组件遵循各自的许可证。", "Windows 10/11 x64 and Ubuntu X11 x64. The application source is MIT licensed; models and third-party components retain their own licenses."),
        ["Ui.Text.8659f29af9af"] = ("密钥使用 Windows DPAPI 或 Linux Secret Service；Linux 密钥服务不可用时仅保留到本次运行结束。", "Credentials use Windows DPAPI or Linux Secret Service. When the Linux secret service is unavailable, they remain in memory until the application exits."),
        ["Ui.Text.87053eb04e5a"] = ("开始截图识别和翻译", "Capture, recognize, and translate"),
        ["Ui.Text.88989b081187"] = ("百度翻译密钥", "Baidu Translation secret"),
        ["Ui.Text.899432d83d98"] = ("快捷操作", "Quick actions"),
        ["Ui.Text.8b6e7cf003a3"] = ("Google Cloud OCR 与翻译凭据", "Google Cloud OCR and Translation credentials"),
        ["Ui.Text.8bc59928b706"] = ("当前方案需要处理", "This mode needs attention"),
        ["Ui.Text.8ccdcad15f65"] = ("本机大模型服务预设", "Local LLM service preset"),
        ["Ui.Text.8d767b02e434"] = ("文字识别提供商", "OCR provider"),
        ["Ui.Text.8f5175f993e2"] = ("显示翻译密钥", "Show translation secret"),
        ["Ui.Text.90b0a90e2226"] = ("检查状态", "Check status"),
        ["Ui.Text.90bd954a5853"] = ("模型名", "Model name"),
        ["Ui.Text.92a84411fed4"] = ("选择本机模型使用 CPU 或通用显卡", "Choose CPU or GPU for the local model"),
        ["Ui.Text.93be5e37dda7"] = ("内容仅在内存中处理", "Content is processed in memory only"),
        ["Ui.Text.94aebfb0a33b"] = ("OCR 凭据：正在检查安全存储…", "OCR credentials: checking secure storage…"),
        ["Ui.Text.955983eac341"] = ("本地 Argos", "Local Argos"),
        ["Ui.Text.966a23e84aed"] = ("目标语言", "Target language"),
        ["Ui.Text.98267fd4ed54"] = ("启动后最小化到托盘", "Start minimized to tray"),
        ["Ui.Text.9866f869b0bd"] = ("正在初始化…", "Initializing…"),
        ["Ui.Text.9a0552ac7454"] = ("选择一键安装的本机多模态模型", "Choose a local multimodal model to install"),
        ["Ui.Text.a1573c4da535"] = ("查看魔搭来源", "View on ModelScope"),
        ["Ui.Text.a27e6084e439"] = ("按 Ctrl+Alt+D 或点击“开始截图”。", "Press Ctrl+Alt+D or select Start capture."),
        ["Ui.Text.a2f2682c6200"] = ("兼容大模型模型名", "Compatible LLM model name"),
        ["Ui.Text.a5088fbb7cd7"] = ("翻译目标语言", "Translation target language"),
        ["Ui.Text.a7ec01a65f09"] = ("保存并应用", "Save and apply"),
        ["Ui.Text.aafd89e24a41"] = ("当前方案用途", "What this scheme does"),
        ["Ui.Text.b406924d6b0e"] = ("选择方案", "Choose scheme"),
        ["Ui.Text.b46b3d4ca814"] = ("打开设置修复问题", "Open settings to fix the issue"),
        ["Ui.Text.b68a94c0e3fb"] = ("启动时检查更新（会访问 GitHub）", "Check for updates at startup (contacts GitHub)"),
        ["Ui.Text.b7600b964f62"] = ("运行后端", "Runtime backend"),
        ["Ui.Text.bd1c1838a09f"] = ("关闭结果卡", "Close result card"),
        ["Ui.Text.c076932bd749"] = ("需要：随安装包提供的离线基础模型。", "Requires: the baseline offline models included with the installer."),
        ["Ui.Text.c2ec0bca09ab"] = ("先看用途，再看处理方式和使用条件。选中后点击应用。", "Compare the purpose, processing method and requirements. Select an option, then apply it."),
        ["Ui.Text.c5b809959cde"] = ("本地 PaddleOCR", "Local PaddleOCR"),
        ["Ui.Text.cb4ba40bf823"] = ("使用说明", "User guide"),
        ["Ui.Text.cd5aa45e3fef"] = ("一键下载并配置", "Download and configure"),
        ["Ui.Text.cebd8d1bf16d"] = ("显示 OCR Secret Key", "Show OCR Secret Key"),
        ["Ui.Text.cec60643bd05"] = ("拖动框选文字区域", "Drag to select a text area"),
        ["Ui.Text.cf15f4b8b319"] = ("切换不会下载模型或验证云端凭据。", "Switching does not download models or validate cloud credentials."),
        ["Ui.Text.cf826c0b58ff"] = ("选择云端翻译时，只发送识别后的纯文字。", "Cloud translation sends recognized text only."),
        ["Ui.Text.d4b3f49cd2e4"] = ("固定", "Pin"),
        ["Ui.Text.d51db0e60727"] = ("隐私与数据", "Privacy & data"),
        ["Ui.Text.d85ff08f9141"] = ("正在检查", "Checking"),
        ["Ui.Text.d95bc1d6f25a"] = ("检查应用更新", "Check for application updates"),
        ["Ui.Text.da4ace1c0a46"] = ("翻译方式", "Translation"),
        ["Ui.Text.dfb699c54378"] = ("设置分类", "Settings categories"),
        ["Ui.Text.e1d715452e7f"] = ("可用方案", "Processing schemes"),
        ["Ui.Text.e27bfc62bfd4"] = ("本地无鉴权服务可留空", "Leave blank for unauthenticated local services"),
        ["Ui.Text.e48775667c9f"] = ("兼容大模型服务地址", "Compatible LLM endpoint"),
        ["Ui.Text.e5145676985f"] = ("当前方案的数据流", "Current data flow"),
        ["Ui.Text.e55a9d121ead"] = ("支持文本翻译与 image_url 多模态识别；图片测试只发送固定合成样本。", "Supports text translation and image_url multimodal OCR. Image tests send a fixed synthetic sample only."),
        ["Ui.Text.e9f6766a6bd4"] = ("全局截图快捷键", "Global capture shortcut"),
        ["Ui.Text.e9f94a5c7ff6"] = ("下载中英 OCR 模型", "Download Chinese/English OCR model"),
        ["Ui.Text.ea9502326203"] = ("启动时校验离线模型", "Verify offline models at startup"),
        ["Ui.Text.ef1361324428"] = ("保存后立即重新注册；冲突时会在当前窗口提示。", "The shortcut is re-registered when saved. Conflicts appear in this window."),
        ["Ui.Text.ef342590f8ff"] = ("云端 OCR 会上传所选截图；云端翻译会上传识别文字。自定义接口的数据去向取决于服务地址，并不一定是本机。", "Cloud OCR uploads the selected image; cloud translation uploads recognized text. A custom endpoint may be local or remote, depending on its address."),
        ["Ui.Text.f14f03fae6b1"] = ("清理下载模型", "Remove downloaded models"),
        ["Ui.Text.f2eabda76179"] = ("打开屏译设置", "Open PingYi settings"),
        ["Ui.Text.f3a95ab3397b"] = ("翻译密钥", "Translation secret"),
        ["Ui.Text.faaa0cb2ce66"] = ("立即检查更新", "Check now"),
        ["Ui.Text.fe43e358e6d1"] = ("魔搭模型库", "ModelScope model library"),
        ["Ui.Text.fef9c07b0efe"] = ("使用帮助与项目", "Help & project"),
        ["Ui.Text.ffdbe22ed8d6"] = ("版本与下载", "Releases & downloads"),
        ["Ui.WorkspaceText.Appearance"] = ("外观与启动", "Appearance & startup"),
        ["Ui.WorkspaceText.AppearanceHint"] = ("调整界面、快捷键和启动行为。", "Adjust your interface, capture shortcut, and startup behavior."),
        ["Ui.WorkspaceText.CleanupHint"] = ("仅清理用户下载的翻译模型；不会删除随软件提供的基础模型。", "Only user-downloaded translation models are removed; bundled models are kept."),
        ["Ui.WorkspaceText.Cloud"] = ("云端服务", "Cloud services"),
        ["Ui.WorkspaceText.CloudHint"] = ("仅在选择相应云端引擎时发送数据。验证凭据会联系服务商。", "Data is sent when its cloud engine is selected. Credential validation contacts the provider."),
        ["Ui.WorkspaceText.Custom"] = ("自定义接口", "Custom endpoint"),
        ["Ui.WorkspaceText.CustomHint"] = ("连接本机服务或兼容接口，分别测试文字与图片能力。", "Connect a local or compatible endpoint; test text and vision separately."),
        ["Ui.WorkspaceText.General"] = ("识别与翻译", "Recognition & translation"),
        ["Ui.WorkspaceText.GeneralHint"] = ("先选识别方式，再选翻译方式与目标语言。", "Choose recognition, translation, and your target language."),
        ["Ui.WorkspaceText.Immediate"] = ("此页选项立即生效，无需另行保存。", "Changes on this page apply immediately."),
        ["Ui.WorkspaceText.ModelHint"] = ("管理离线识别、离线翻译和完全版的本机大模型。", "Manage offline OCR, translation, and Complete edition local models."),
        ["Ui.WorkspaceText.Models"] = ("本地模型", "Local models"),
        ["Ui.WorkspaceText.Preferences"] = ("偏好设置", "Preferences"),
        ["Ui.WorkspaceText.ProcessLabel"] = ("处理流程", "PROCESSING FLOW"),
        ["Ui.WorkspaceText.Reading"] = ("让阅读，不止于一种语言。", "Read beyond one language."),
        ["Ui.WorkspaceText.Refresh"] = ("刷新状态", "Refresh status"),
        ["Ui.WorkspaceText.SaveHint"] = ("其他配置修改后，请保存并应用。Ctrl+S 可快速保存。", "Save and apply other configuration changes. Shortcut: Ctrl+S."),
        ["Ui.WorkspaceText.SecretHint"] = ("点击“显示”后编辑密钥，再保存或验证。密钥沿用系统安全存储。", "Select Reveal to edit a key, then save or validate. Keys use the existing system secure store."),
        ["Ui.WorkspaceText.Settings"] = ("设置", "Settings"),
    };

    private static void ApplyLanguageResources()
    {
        if (Avalonia.Application.Current?.Resources is not { } resources) return;
        foreach (var (key, pair) in UiResources)
            resources[key] = IsEnglish ? pair.English : pair.Chinese;
    }

    private static readonly Lazy<IReadOnlyDictionary<string, string>> CanonicalLabels = new(() =>
        EnglishText.Select(p => (En: p.Value, Zh: p.Key))
            .Concat(UiResources.Values.Select(p => (En: p.English, Zh: p.Chinese)))
            .GroupBy(p => p.En, StringComparer.Ordinal)
            .ToDictionary(g => g.Key, g => g.First().Zh, StringComparer.Ordinal));
    private static readonly Lazy<IReadOnlyDictionary<string, string>> ResourceTranslations = new(() =>
        UiResources.Values.GroupBy(p => p.Chinese, StringComparer.Ordinal)
            .ToDictionary(g => g.Key, g => g.First().English, StringComparer.Ordinal));

    private static string CanonicalLabel(string text) => CanonicalLabels.Value.TryGetValue(text, out var value) ? value : text;
    private static string? ResourceTranslation(string text) => ResourceTranslations.Value.TryGetValue(text, out var value) ? value : null;
}
